Route1_Text_WorkAtPokeMartTakeSample::
    .string "Hi!\n"
    .string "I work at a POKéMON MART.\p"
    .string "It's part of a convenient chain\n"
    .string "selling all sorts of items.\p"
    .string "Please, visit us in VIRIDIAN CITY.\p"
    .string "I know, I'll give you a sample.\n"
    .string "Here you go!$"

Route1_Text_ComeSeeUsIfYouNeedPokeBalls::
    .string "Please come see us if you need\n"
    .string "POKé BALLS for catching POKéMON.$"

Route1_Text_PutPotionAway::
    .string "{PLAYER} put the POTION away in\n"
    .string "the BAG's ITEMS POCKET.$"

Route1_Text_CanJumpFromLedges::
    .string "See those ledges along the road?\p"
    .string "It's a bit scary, but you can jump\n"
    .string "from them.\p"
    .string "You can get back to PALLET TOWN\n"
    .string "quicker that way.$"

Route1_Text_RouteSign::
    .string "ROUTE 1\n"
    .string "PALLET TOWN - VIRIDIAN CITY$"

Route1_Text_JakeIntro::
    .string "Hey! I see you picked up a starter\n"
    .string "from PROF. OAK's lab!\p"
    .string "Want to test it out?$"

Route1_Text_JakeDefeat::
    .string "No way… I lost!\n"
    .string "Maybe I should get a\l"
    .string "starter too...$"

Route1_Text_JakePostBattle::
    .string "You're really strong.\n"
    .string "I guess starters are a big deal!$"

