PalletTown_Text_OakDontGoOut::
    .string "OAK: Hey! Wait!\n"
    .string "Don't go out!$"

PalletTown_Text_OakGrassUnsafeNeedMon::
    .string "OAK: It's unsafe!\n"
    .string "Wild POKéMON live in tall grass!\p"
    .string "Ever since that business in\n"
    .string "Lumiose, POKéMON of higher\p"
    .string "levels have been sighted\n"
    .string "nearby!\p"
    .string "You need your own POKéMON for\n"
    .string "your protection.\p"
    .string "I know!\n"
    .string "Here, come with me!$"

PalletTown_Text_RaisingMonsToo::
    .string "I'm raising POKéMON, too.\p"
    .string "When they get strong, they can\n"
    .string "protect me.$"

PalletTown_Text_CanStoreItemsAndMonsInPC::
    .string "Technology is incredible!\p"
    .string "You can now store and recall items\n"
    .string "and POKéMON as data via PC.\p"
    .string "Wish I had such tech when\n"
    .string "I was a kid!$"

PalletTown_Text_FatManReturn::
    .string "I am at a crossroads!\n"
    .string "I just can't decide which region\l"
    .string "I like most.\p"
    .string "I love my home region of Kanto.\n"
    .string "But I can't get enough of the old\l"
    .string "monuments in Johto.\p"
    .string "Hoenn has beautiful waters.\n"
    .string "Sinnoh beautiful mountains.\p"
    .string "Unova is home to some cool\n"
    .string "looking LEGENDARY POKéMON.\p"
    .string "Kalos has mega evolved forms of\n"
    .string "POKéMON a plenty and Alola I hear\l"
    .string "is such a tropical escape.\p"
    .string "Galar has such a noble history.\n"
    .string "Paldea I hear has a nice POKéMON\l"
    .string "academy where you can learn a lot!\p"
    .string "Oh boy! Simply such a hard decision!$"

PalletTown_Text_OakPokemonResearchLab::
    .string "OAK POKéMON RESEARCH LAB$"

PalletTown_Text_PlayersHouse::
    .string "{PLAYER}'s house$"

PalletTown_Text_RivalsHouse::
    .string "{RIVAL}'s house$"

PalletTown_Text_TownSign::
    .string "PALLET TOWN\n"
    .string "Every journey ought to start from\p"
    .string "humble roots!$"

PalletTown_Text_OakLetMeSeePokedex::
    .string "OAK: Ah, {PLAYER}!\n"
    .string "You're back, are you?\p"
    .string "How much have you filled in your\n"
    .string "POKéDEX?\p"
    .string "May I see it?\p"
    .string "Let's see…$"

PalletTown_Text_CaughtXPuttingInHonestEffort::
    .string "You've caught {STR_VAR_2}…\p"
    .string "Hm, it looks as if you're putting\n"
    .string "in an honest effort.\p"
    .string "When you manage to fill it some\n"
    .string "more, come show me, please.$"

PalletTown_Text_CaughtXImpressiveFollowMe::
    .string "You've caught… {STR_VAR_2}!?\n"
    .string "Now, this is impressive!\p"
    .string "There's something I wanted to ask\n"
    .string "of you, {PLAYER}.\p"
    .string "Come.\n"
    .string "Follow me.$"

PalletTown_Text_OakYouEnjoyingTraveling::
    .string "OAK: Ah, {PLAYER}!\n"
    .string "You seem to be enjoying traveling.\p"
    .string "Knowing you, {PLAYER}, I can easily\n"
    .string "imagine you going out to even more\l"
    .string "exotic locales.\p"
    .string "Good for you, good for you.\n"
    .string "Hohoho.$"

